#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for an endorsing organization
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org1_name }}"
    organization_msp_id: "{{ org1_msp_id }}"
    ca_name: "{{ org1_ca_name }}"
    peer_name: "{{ org1_peer_name }}"
    peers: 2
    wallet: "{{ wallet_dir }}"
  vars_files:
    - ../config/common-vars.yml
    - ../config/digibank-vars.yml
    - ../config/auth-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization
