#
# SPDX-License-Identifier: Apache-2.0
#
---
# K8S Variables
namespace: 'caasdemo' # i.e. needed by multiple orgs so can't just live in a per org file
image_pull_secret: 'pullimg-secret-ansible'
image_registry: stg.icr.io 


# IBM Cloud configuration
region: 'us-south'
service_id: 'demo-caas-id-7'
key_name: 'demo-caas-api-key'
# cloud_api_key: api-key-for-ibm-cloud-is-needed-here

# these values are arbitray they are only used to generate the secret
image_registry_email: barney@flintsone.org
image_registry_username: iamapikey
