#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for an endorsing organization
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org2_name }}"
    organization_msp_id: "{{ org2_msp_id }}"
    ca_name: "{{ org2_ca_name }}"
    peer_name: "{{ org2_peer_name }}"
    peers: 2
    wallet: "{{ cfg_dir }}/ibp_wallet"    
  vars_files:
    - ../config/common-vars.yml
    - ../config/magnetocorp-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization
