#
# SPDX-License-Identifier: Apache-2.0
#
---
# These are variables used by IBP in different orgs
# i.e. needed by multiple orgs so can't just live in a per org file
ordering_org_name: "CAAS Ordering Org"
ordering_service_name: "CAAS Ordering Service"
org1_name: "DigiBank"
org1_msp_id: DigiBankMSP

channel_name: caasnetwork

# Latest Images
# ca_version: "1.4.11-0"
# peer_version: "2.2.2-0"
# ordering_service_version: "2.2.2-0"

ca_version: 1.4.9-7
peer_version: 2.2.2-2
ordering_service_version: 2.2.2-2