#  And All peers on channel "simplechannel" have installed the chaincode "simple"
---
- name: Register application
  hosts: localhost
  vars_files:
    - ../config/ibp-vars.yml
    - ../config/ibp-org1-vars.yml
  tasks:
    - name: Register a new identity
      ibm.blockchain_platform.registered_identity:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        certificate_authority: "{{ org1_ca_name }}"
        registrar: "../_cfg/{{ org1_ca_name }} Admin.json"
        enrollment_id: "{{ enroll_id }}"
        enrollment_secret: "wibble"
        max_enrollments: "{{ application_max_enrollments }}"
        type: "{{ application_enrollment_type }}"

    - name: Enroll an identity
      ibm.blockchain_platform.enrolled_identity:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        certificate_authority: "{{ org1_ca_name }}"
        name: "{{ name }}"
        enrollment_id: "{{ enroll_id }}"
        enrollment_secret: "wibble"
        path: "{{ home_dir }}/_cfg/{{ name }}_tls.json"
        tls: true
        hosts:
          - nodecontract-srvc.caasdemo.svc.cluster.local
          - nodecontract-srvc.caasdemo.svc.cluster
          - nodecontract-srvc.caasdemo.svc
          - nodecontract-srvc.caasdemo
          - nodecontract-srvc

